### ISSUE TITLE
android13 oneui 5.1崩潰

### ISSUE THREAD

**Issue by yue27149** [sbmatch/DeviceOptimizeHelper#4]
[Device Brand]: samsung
[Device Model]: SM-A5360
[Display]: TP1A.220624.014.A5360ZHS7CWI1
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN_#Hans
[Process ID]: 23205
[User ID]: 0
[CPU ABI]: none
[Package Name]: ma.DeviceOptimizeHelper
[Version Name]: 1.1.7_b665896
[Version Code]: 1
[Target SDK]: 34
[Min SDK]: 26
[Error Type]: JVM
[Crash Time]: 2024-01-19T07:39:04.774
[Stack Trace]:
java.lang.RuntimeException: Only one Looper may be created per thread
	at android.os.Looper.prepare(Looper.java:123)
	at android.os.Looper.prepare(Looper.java:118)
	at ma.DeviceOptimizeHelper.MainActivity.getResIdReflect(MainActivity.java:588)
	at ma.DeviceOptimizeHelper.MainActivity$HeaderFragment.onCreatePreferences(MainActivity.java:437)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
	at android.app.Activity.performStart(Activity.java:8616)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4204)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by sbmatch** [comment]
收到，已定位到问题代码

**Comment by sbmatch** [comment]
请使用最新版本
