### ISSUE TITLE
三星安卓12  1.2.0 崩溃 

### ISSUE THREAD

**Issue by hyplant** [sbmatch/DeviceOptimizeHelper#8]
`三星`手机，安卓`12`，OneUI`4.1`
刷入了[`miui core`](https://www.pling.com/p/1537512/) `5.7` 以使用`小米天气` `小米社区` `小米计算器`等app，报错似乎和这个有关

ma.DeviceOptimizeHelper: `1.2.0_29cf8c2`
```
供应商: samsung, 型号: SM-N9760, Android版本: 12, SDK版本: 31
java.lang.ExceptionInInitializerError
	at ma.DeviceOptimizeHelper.MainActivity$HeaderFragment.onCreatePreferences(Unknown Source:6)
	at androidx.preference.w.onCreate(Unknown Source:73)
	at androidx.fragment.app.Fragment.performCreate(Unknown Source:26)
	at androidx.fragment.app.c1.e(Unknown Source:40)
	at androidx.fragment.app.c1.k(Unknown Source:139)
	at androidx.fragment.app.w0.t(Unknown Source:586)
	at androidx.fragment.app.w0.I(Unknown Source:81)
	at androidx.fragment.app.w0.s(Unknown Source:75)
	at androidx.fragment.app.w0.o(Unknown Source:64)
	at androidx.fragment.app.c0.onStart(Unknown Source:33)
	at f.q.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
	at android.app.Activity.performStart(Activity.java:8315)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: miui.security.AppRunningControlManager
	at t2.g.<clinit>(Unknown Source:57)
	... 26 more
Caused by: java.lang.ClassNotFoundException: miui.security.AppRunningControlManager
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.Class.forName(Class.java:379)
	at t2.g.<clinit>(Unknown Source:41)
	... 26 more
Caused by: java.lang.ClassNotFoundException: miui.security.AppRunningControlManager
	... 30 more

```

另外使用`termux`运行命令
```
su system -c "app_process -Djava.class.path=/data/local/tmp/classes.dex / ma.DeviceOptimizeHelper.Main"
```
只出现`Killed`
尝试使用adb执行
```
app_process -Djava.class.path=/data/local/tmp/classes.dex ma.DeviceOptimizeHelper.Main
```
也报错`Error changing dalvik-cache ownership : Operation not permitted
Aborted`

**Comment by sbmatch** [comment]
看错了，问题已经定位，中午下班休息的时候修

**Comment by sbmatch** [comment]
使用最新的v1.2.1版本已经修复问题[@cc1a876](https://github.com/sbmatch/DeviceOptimizeHelper/commit/cc1a876c1df7dac9cfb59f5f4a1a9c3445063b28)

**Comment by hyplant** [comment]
经测试，没有问题
